name = "image-upload-tool"
type = "javascript"

account_id = "<YOUR_ACCOUNT_ID>"
workers_dev = true
compatibility_date = "2024-07-12"

[site]
bucket = "./public"
entry-point = "functions"

[env.production]
compatibility_date = "2024-07-12"
